////----------------------------------------------------------------------
//// This file has been automatically generated by
//// VerifStudio Software Version 0.63, Accelver Systems Inc.
//// Any modifications that you make to this file may be
//// overwritten by the tool when regenerating the files. 
////----------------------------------------------------------------------

`ifndef AHB_MASTER_TRANSACTION__SV
`define AHB_MASTER_TRANSACTION__SV

class ahb_master_transaction#(AHB_ADDR_WIDTH=16,AHB_DATA_WIDTH=16) extends uvm_sequence_item;

    // Register the class ahb_master_transaction with the factory.
    `uvm_object_param_utils_begin(ahb_master_transaction#(AHB_ADDR_WIDTH,AHB_DATA_WIDTH))
    `uvm_object_utils_end

    // The Constructor for this Class.
    function new(string name="ahb_master_transaction");
        super.new(name);
    endfunction: new

endclass: ahb_master_transaction


`endif